### ISSUE TITLE
The service "alpixel_seo.helper" has a dependency on a non-existent parameter "enabled_locales".

### ISSUE THREAD

**Issue by pije76** [alpixel/AlpixelSeoBundle#9]
Error message "The service "alpixel_seo.helper" has a dependency on a non-existent parameter "enabled_locales" when I run php bin/console doctrine:schema:update --force --dump-sql

**Comment by AlexBDev** [comment]
You need to provide an array of available locales in your parameters.yml.

Example:

```yaml
parameters:
    enabled_locales:
        - fr
        - en
```
